import 'package:uuid/uuid.dart';

import '../../core/constants.dart';
import '../../models/accounting_entry.dart';
import '../../models/famille.dart';
import '../../models/member.dart';
import '../../models/region_eglise.dart';
import '../../models/district_eglise.dart';
import '../../models/assemblee_locale.dart';
import '../../models/profil_utilisateur.dart';
import '../../models/program.dart';
import '../../models/compte_comptable.dart';
import '../../models/journal_comptable.dart';
import '../../models/centre_analytique.dart';
import '../../models/tiers.dart';
import '../../models/ecriture_comptable.dart';
import '../../models/compta_enums.dart';
import 'data_service.dart';

class InMemoryDataService implements DataService {
  InMemoryDataService() {
    _seed();
  }

  final _members = <Member>[];
  final _programs = <Program>[];
  final _entries = <AccountingEntry>[];
  final List<CompteComptable> _comptesComptables = [
    // Actif (tresorerie, creances, immobilisations simples)
    const CompteComptable(
      id: 'compte_531',
      numero: '531',
      intitule: 'Caisse',
      nature: NatureCompte.actif,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_5121',
      numero: '5121',
      intitule: 'Banque - Compte principal',
      nature: NatureCompte.actif,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_411',
      numero: '411',
      intitule: 'Membres / adherents',
      nature: NatureCompte.actif,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_401',
      numero: '401',
      intitule: 'Fournisseurs',
      nature: NatureCompte.passif,
      niveau: 3,
    ),

    // Charges
    const CompteComptable(
      id: 'compte_613',
      numero: '613',
      intitule: 'Loyers et locations',
      nature: NatureCompte.charge,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_615',
      numero: '615',
      intitule: 'Entretien et reparations',
      nature: NatureCompte.charge,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_624',
      numero: '624',
      intitule: 'Transports',
      nature: NatureCompte.charge,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_645',
      numero: '645',
      intitule: 'Indemnites et aides',
      nature: NatureCompte.charge,
      niveau: 3,
    ),

    // Produits (recettes d'eglise)
    const CompteComptable(
      id: 'compte_701',
      numero: '701',
      intitule: 'Dimes',
      nature: NatureCompte.produit,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_702',
      numero: '702',
      intitule: 'Offrandes de culte',
      nature: NatureCompte.produit,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_706',
      numero: '706',
      intitule: 'Dons et liberalites',
      nature: NatureCompte.produit,
      niveau: 3,
    ),
    const CompteComptable(
      id: 'compte_758',
      numero: '758',
      intitule: 'Autres produits de gestion',
      nature: NatureCompte.produit,
      niveau: 3,
    ),
  ];
  final List<JournalComptable> _journauxComptables = [
    const JournalComptable(
      id: 'journal_caisse',
      code: 'CAI',
      intitule: 'Journal de caisse',
      type: TypeJournalComptable.caisse,
    ),
    const JournalComptable(
      id: 'journal_banque',
      code: 'BAN',
      intitule: 'Journal de banque',
      type: TypeJournalComptable.banque,
    ),
    const JournalComptable(
      id: 'journal_od',
      code: 'OD',
      intitule: 'Journal des operations diverses',
      type: TypeJournalComptable.operationsDiverses,
    ),
  ];
  final List<CentreAnalytique> _centresAnalytiques = [
    // Centres = assemblees locales
    const CentreAnalytique(
      id: 'centre_assemblee_cotonou_centre',
      code: 'ASS-COT-CENTRE',
      nom: 'Assemblee de Cotonou Centre',
      type: TypeCentreAnalytique.assembleeLocale,
      idAssembleeLocale: 'assemblee_cotonou_centre',
    ),
    const CentreAnalytique(
      id: 'centre_assemblee_agla',
      code: 'ASS-AGLA',
      nom: "Assemblee d'Agla",
      type: TypeCentreAnalytique.assembleeLocale,
      idAssembleeLocale: 'assemblee_agla',
    ),
    const CentreAnalytique(
      id: 'centre_assemblee_fidjrosse',
      code: 'ASS-FIDJROSSE',
      nom: 'Assemblee de Fidjrosse',
      type: TypeCentreAnalytique.assembleeLocale,
      idAssembleeLocale: 'assemblee_fidjrosse',
    ),

    // Centres = projets
    const CentreAnalytique(
      id: 'centre_projet_construction_cotonou_centre',
      code: 'PROJ-CONSTR-COT-CENTRE',
      nom: 'Projet construction temple Cotonou Centre',
      type: TypeCentreAnalytique.projet,
      idAssembleeLocale: 'assemblee_cotonou_centre',
      description: "Travaux de construction / extension de l'eglise.",
    ),
    const CentreAnalytique(
      id: 'centre_projet_evangelisation_2025',
      code: 'PROJ-EV-2025',
      nom: 'Projet evangelisation 2025',
      type: TypeCentreAnalytique.projet,
      description: "Campagnes d'evangelisation pour l'annee 2025.",
    ),
  ];
  final List<Tiers> _tiers = [
    // Tiers lies a des fideles (membres)
    const Tiers(
      id: 'tiers_membre_001',
      nom: 'Membre adherent 001',
      type: TypeTiers.membre,
      idAssembleeLocale: 'assemblee_cotonou_centre',
      idFideleLie: 'fidele_001',
    ),
    const Tiers(
      id: 'tiers_membre_002',
      nom: 'Membre adherent 002',
      type: TypeTiers.membre,
      idAssembleeLocale: 'assemblee_agla',
      idFideleLie: 'fidele_007',
    ),

    // Fournisseurs
    const Tiers(
      id: 'tiers_fournisseur_sonorisation',
      nom: 'Fournisseur SONO Services',
      type: TypeTiers.fournisseur,
      telephone: '+229 01 23 45 67',
      adresse: 'Cotonou',
    ),
    const Tiers(
      id: 'tiers_fournisseur_impression',
      nom: 'Imprimerie Bethanie',
      type: TypeTiers.fournisseur,
      telephone: '+229 98 76 54 32',
      adresse: 'Abomey-Calavi',
    ),

    // Bailleur / partenaire
    const Tiers(
      id: 'tiers_bailleur_fondation_x',
      nom: 'Fondation Espoir',
      type: TypeTiers.bailleur,
      email: 'contact@fondation-espoir.org',
    ),
  ];
  final List<EcritureComptable> _ecrituresComptables = [
    // 1) Offrandes de culte en especes (Assemblee Cotonou Centre)
    EcritureComptable(
      id: 'ecriture_001',
      date: DateTime(2025, 3, 2),
      idJournal: 'journal_caisse',
      referencePiece: 'REC-2025-03-02-001',
      libelle: 'Offrandes du culte dominical',
      idAssembleeLocale: 'assemblee_cotonou_centre',
      idCentreAnalytiquePrincipal: 'centre_assemblee_cotonou_centre',
      lignes: const [
        LigneEcritureComptable(
          id: 'lig_001_1',
          idCompteComptable: 'compte_531',
          debit: 150000,
          credit: 0,
          libelle: 'Encaissement des offrandes en especes',
          modePaiement: ModePaiement.especes,
          idCentreAnalytique: 'centre_assemblee_cotonou_centre',
        ),
        LigneEcritureComptable(
          id: 'lig_001_2',
          idCompteComptable: 'compte_702',
          debit: 0,
          credit: 150000,
          libelle: 'Produit des offrandes',
          idCentreAnalytique: 'centre_assemblee_cotonou_centre',
        ),
      ],
    ),

    // 2) Paiement facture de sonorisation par banque (projet construction)
    EcritureComptable(
      id: 'ecriture_002',
      date: DateTime(2025, 3, 5),
      idJournal: 'journal_banque',
      referencePiece: 'FAC-SONO-2025-03',
      libelle: 'Reglement facture sonorisation culte special',
      idAssembleeLocale: 'assemblee_cotonou_centre',
      idCentreAnalytiquePrincipal: 'centre_projet_construction_cotonou_centre',
      lignes: const [
        LigneEcritureComptable(
          id: 'lig_002_1',
          idCompteComptable: 'compte_613',
          debit: 80000,
          credit: 0,
          libelle: 'Charge de sonorisation',
          idCentreAnalytique: 'centre_projet_construction_cotonou_centre',
          idTiers: 'tiers_fournisseur_sonorisation',
        ),
        LigneEcritureComptable(
          id: 'lig_002_2',
          idCompteComptable: 'compte_5121',
          debit: 0,
          credit: 80000,
          libelle: 'Paiement par banque',
          modePaiement: ModePaiement.virementBancaire,
        ),
      ],
    ),

    // 3) Indemnite versee a un membre vulnerable
    EcritureComptable(
      id: 'ecriture_003',
      date: DateTime(2025, 3, 10),
      idJournal: 'journal_caisse',
      referencePiece: 'AIDE-SOC-2025-03-10',
      libelle: 'Aide sociale a un membre',
      idAssembleeLocale: 'assemblee_agla',
      idCentreAnalytiquePrincipal: 'centre_assemblee_agla',
      lignes: const [
        LigneEcritureComptable(
          id: 'lig_003_1',
          idCompteComptable: 'compte_645',
          debit: 30000,
          credit: 0,
          libelle: 'Aide a un membre vulnerable',
          idCentreAnalytique: 'centre_assemblee_agla',
          idTiers: 'tiers_membre_001',
        ),
        LigneEcritureComptable(
          id: 'lig_003_2',
          idCompteComptable: 'compte_531',
          debit: 0,
          credit: 30000,
          libelle: 'Decaissement de caisse',
          modePaiement: ModePaiement.especes,
        ),
      ],
    ),
  ];
  final _familles = <Famille>[];
  final _regions = <RegionEglise>[];
  final _districts = <DistrictEglise>[];
  final _assembleesLocales = <AssembleeLocale>[];
  final _profilsUtilisateurs = <ProfilUtilisateur>[];
  final _uuid = const Uuid();

  List<Famille> get familles => List<Famille>.unmodifiable(_familles);
  List<RegionEglise> get regions => List<RegionEglise>.unmodifiable(_regions);
  List<DistrictEglise> get districts =>
      List<DistrictEglise>.unmodifiable(_districts);
  List<AssembleeLocale> get assembleesLocales =>
      List<AssembleeLocale>.unmodifiable(_assembleesLocales);
  List<CompteComptable> get comptesComptables => _comptesComptables;
  List<JournalComptable> get journauxComptables => _journauxComptables;
  List<CentreAnalytique> get centresAnalytiques => _centresAnalytiques;
  List<Tiers> get tiers => _tiers;
  List<EcritureComptable> get ecrituresComptables => _ecrituresComptables;
  @override
  Future<List<Famille>> getFamilies() async {
    return List<Famille>.unmodifiable(_familles);
  }

  @override
  Future<List<RegionEglise>> getRegions() async {
    return List<RegionEglise>.unmodifiable(_regions);
  }

  @override
  Future<List<DistrictEglise>> getDistricts() async {
    return List<DistrictEglise>.unmodifiable(_districts);
  }

  @override
  Future<List<AssembleeLocale>> getAssembleesLocales() async {
    return List<AssembleeLocale>.unmodifiable(_assembleesLocales);
  }

  @override
  Future<List<ProfilUtilisateur>> getProfilsUtilisateurs() async {
    return List<ProfilUtilisateur>.unmodifiable(_profilsUtilisateurs);
  }

  void _seed() {
    if (_members.isNotEmpty) return;

    _regions.addAll([
      const RegionEglise(id: 'region_sud', nom: 'Region Sud', code: 'REG-SUD'),
      const RegionEglise(
        id: 'region_centre',
        nom: 'Region Centre',
        code: 'REG-CENTRE',
      ),
      const RegionEglise(id: 'region_nord', nom: 'Region Nord', code: 'REG-NORD'),
    ]);

    _districts.addAll([
      const DistrictEglise(
        id: 'district_cotonou',
        nom: 'District de Cotonou',
        code: 'DIS-COT',
        idRegion: 'region_sud',
      ),
      const DistrictEglise(
        id: 'district_calavi',
        nom: 'District d Abomey-Calavi',
        code: 'DIS-CAL',
        idRegion: 'region_sud',
      ),
      const DistrictEglise(
        id: 'district_ouidah',
        nom: 'District de Ouidah',
        code: 'DIS-OUI',
        idRegion: 'region_sud',
      ),
      const DistrictEglise(
        id: 'district_porto_novo',
        nom: 'District de Porto-Novo',
        code: 'DIS-PNO',
        idRegion: 'region_centre',
      ),
      const DistrictEglise(
        id: 'district_bohicon',
        nom: 'District de Bohicon',
        code: 'DIS-BOH',
        idRegion: 'region_centre',
      ),
      const DistrictEglise(
        id: 'district_parakou',
        nom: 'District de Parakou',
        code: 'DIS-PAR',
        idRegion: 'region_nord',
      ),
      const DistrictEglise(
        id: 'district_natitingou',
        nom: 'District de Natitingou',
        code: 'DIS-NAT',
        idRegion: 'region_nord',
      ),
    ]);

    _assembleesLocales.addAll([
      const AssembleeLocale(
        id: 'assemblee_cotonou_centre',
        nom: 'Assemblee de Cotonou Centre',
        code: 'ASS-COT-CENTRE',
        idDistrict: 'district_cotonou',
        ville: 'Cotonou',
        quartier: 'Centre-ville',
        telephone: '+229 01 00 00 01',
        email: 'cotonou.centre@example.com',
      ),
      const AssembleeLocale(
        id: 'assemblee_agla',
        nom: 'Assemblee d Agla',
        code: 'ASS-AGLA',
        idDistrict: 'district_cotonou',
        ville: 'Cotonou',
        quartier: 'Agla',
      ),
      const AssembleeLocale(
        id: 'assemblee_fidjrosse',
        nom: 'Assemblee de Fidjrosse',
        code: 'ASS-FIDJROSSE',
        idDistrict: 'district_cotonou',
        ville: 'Cotonou',
        quartier: 'Fidjrosse',
      ),
      const AssembleeLocale(
        id: 'assemblee_calavi_centre',
        nom: 'Assemblee de Calavi Centre',
        code: 'ASS-CAL-CENTRE',
        idDistrict: 'district_calavi',
        ville: 'Abomey-Calavi',
        quartier: 'Centre',
      ),
      const AssembleeLocale(
        id: 'assemblee_akassato',
        nom: 'Assemblee d Akassato',
        code: 'ASS-AKA',
        idDistrict: 'district_calavi',
        ville: 'Abomey-Calavi',
        quartier: 'Akassato',
      ),
      const AssembleeLocale(
        id: 'assemblee_porto_novo_koutongou',
        nom: 'Assemblee de Porto-Novo Koutongou',
        code: 'ASS-PNO-KOU',
        idDistrict: 'district_porto_novo',
        ville: 'Porto-Novo',
      ),
      const AssembleeLocale(
        id: 'assemblee_ouidah_centre',
        nom: 'Assemblee de Ouidah Centre',
        code: 'ASS-OUI-CENTRE',
        idDistrict: 'district_ouidah',
        ville: 'Ouidah',
      ),
      const AssembleeLocale(
        id: 'assemblee_parakou_centre',
        nom: 'Assemblee de Parakou Centre',
        code: 'ASS-PAR-CENTRE',
        idDistrict: 'district_parakou',
        ville: 'Parakou',
      ),
      const AssembleeLocale(
        id: 'assemblee_natitingou_centre',
        nom: 'Assemblee de Natitingou Centre',
        code: 'ASS-NAT-CENTRE',
        idDistrict: 'district_natitingou',
        ville: 'Natitingou',
      ),
    ]);

    _profilsUtilisateurs.addAll(const [
      ProfilUtilisateur(
        id: 'profil_admin',
        nom: 'Admin national (simulation)',
        role: RoleUtilisateur.adminNational,
      ),
      ProfilUtilisateur(
        id: 'profil_responsable_region_sud',
        nom: 'Responsable Region Sud',
        role: RoleUtilisateur.responsableRegion,
        idRegion: 'region_sud',
      ),
      ProfilUtilisateur(
        id: 'profil_surintendant_district_cotonou',
        nom: 'Surintendant District Cotonou',
        role: RoleUtilisateur.surintendantDistrict,
        idRegion: 'region_sud',
        idDistrict: 'district_cotonou',
      ),
      ProfilUtilisateur(
        id: 'profil_tresorier_cotonou_centre',
        nom: 'Tresorier Assemblee Cotonou Centre',
        role: RoleUtilisateur.tresorierAssemblee,
        idRegion: 'region_sud',
        idDistrict: 'district_cotonou',
        idAssembleeLocale: 'assemblee_cotonou_centre',
      ),
    ]);

    _members.addAll([
      Member(
        id: 'fidele_001',
        fullName: 'Jean-Baptiste Adjibi',
        gender: Gender.male,
        birthDate: DateTime(1978, 5, 12),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2000, 1, 21),
        phone: '+229 61000001',
        email: 'jean.adjibi@example.com',
        address: 'Porto-Novo',
        dateNaissance: DateTime(1978, 5, 12),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1999, 3, 14),
        dateBapteme: DateTime(2000, 1, 21),
        dateMainAssociation: DateTime(2002, 6, 9),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2010, 9, 1),
        role: RoleFidele.pasteur,
        idFamille: 'famille_adjibi',
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
      ),
      Member(
        id: 'fidele_002',
        fullName: 'Marcelline Adjibi',
        gender: Gender.female,
        birthDate: DateTime(1980, 3, 4),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2001, 3, 2),
        phone: '+229 61000002',
        email: 'marcelline.adjibi@example.com',
        address: 'Porto-Novo',
        dateNaissance: DateTime(1980, 3, 4),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2000, 5, 12),
        dateBapteme: DateTime(2001, 3, 2),
        dateMainAssociation: DateTime(2002, 7, 20),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2010, 9, 1),
        role: RoleFidele.diaconesse,
        idFamille: 'famille_adjibi',
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
      ),
      Member(
        id: 'fidele_003',
        fullName: 'Cyriaque Hounkpe',
        gender: Gender.male,
        birthDate: DateTime(1968, 8, 10),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1989, 6, 15),
        phone: '+229 61000003',
        email: 'cyriaque.hounkpe@example.com',
        address: 'Cotonou',
        dateNaissance: DateTime(1968, 8, 10),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1988, 5, 12),
        dateBapteme: DateTime(1989, 6, 15),
        dateMainAssociation: DateTime(1990, 1, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2005, 3, 10),
        role: RoleFidele.ancien,
        vulnerabilites: {VulnerabiliteFidele.troisiemeAge},
        idFamille: 'famille_hounkpe',
        idAssembleeLocale: 'assemblee_cotonou_centre',
      ),
      Member(
        id: 'fidele_004',
        fullName: 'Clarisse Hounkpe',
        gender: Gender.female,
        birthDate: DateTime(1970, 2, 22),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1990, 8, 19),
        phone: '+229 61000004',
        email: 'clarisse.hounkpe@example.com',
        address: 'Cotonou',
        dateNaissance: DateTime(1970, 2, 22),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1989, 9, 1),
        dateBapteme: DateTime(1990, 8, 19),
        dateMainAssociation: DateTime(1991, 2, 5),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2005, 3, 10),
        role: RoleFidele.membre,
        idFamille: 'famille_hounkpe',
        idAssembleeLocale: 'assemblee_cotonou_centre',
      ),
      Member(
        id: 'fidele_005',
        fullName: 'Rodrigue Gbeto',
        gender: Gender.male,
        birthDate: DateTime(1972, 7, 1),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1993, 4, 3),
        phone: '+229 61000005',
        email: 'rodrigue.gbeto@example.com',
        address: 'Abomey-Calavi',
        dateNaissance: DateTime(1972, 7, 1),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1991, 11, 12),
        dateBapteme: DateTime(1993, 4, 3),
        dateMainAssociation: DateTime(1994, 7, 18),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2008, 6, 1),
        role: RoleFidele.ancien,
        idFamille: 'famille_gbeto',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_006',
        fullName: 'Sophie Gbeto',
        gender: Gender.female,
        birthDate: DateTime(1975, 9, 12),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1995, 2, 5),
        phone: '+229 61000006',
        email: 'sophie.gbeto@example.com',
        address: 'Abomey-Calavi',
        dateNaissance: DateTime(1975, 9, 12),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1993, 9, 10),
        dateBapteme: DateTime(1995, 2, 5),
        dateMainAssociation: DateTime(1996, 6, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2008, 6, 1),
        role: RoleFidele.diaconesse,
        idFamille: 'famille_gbeto',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_007',
        fullName: 'Michel Dossou',
        gender: Gender.male,
        birthDate: DateTime(1982, 1, 19),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2002, 3, 2),
        phone: '+229 61000007',
        email: 'michel.dossou@example.com',
        address: 'Cotonou',
        dateNaissance: DateTime(1982, 1, 19),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2000, 8, 14),
        dateBapteme: DateTime(2002, 3, 2),
        dateMainAssociation: DateTime(2003, 1, 9),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2013, 5, 12),
        role: RoleFidele.diacre,
        idFamille: 'famille_dossou',
        idAssembleeLocale: 'assemblee_agla',
      ),
      Member(
        id: 'fidele_008',
        fullName: 'Elise Dossou',
        gender: Gender.female,
        birthDate: DateTime(1984, 6, 7),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2004, 4, 11),
        phone: '+229 61000008',
        email: 'elise.dossou@example.com',
        address: 'Cotonou',
        dateNaissance: DateTime(1984, 6, 7),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2002, 10, 5),
        dateBapteme: DateTime(2004, 4, 11),
        dateMainAssociation: DateTime(2005, 2, 4),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2013, 5, 12),
        role: RoleFidele.membre,
        idFamille: 'famille_dossou',
        idAssembleeLocale: 'assemblee_agla',
      ),
      Member(
        id: 'fidele_009',
        fullName: 'Florent Akpo',
        gender: Gender.male,
        birthDate: DateTime(1965, 12, 30),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1986, 2, 22),
        phone: '+229 61000009',
        email: 'florent.akpo@example.com',
        address: 'Abomey',
        dateNaissance: DateTime(1965, 12, 30),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1984, 9, 16),
        dateBapteme: DateTime(1986, 2, 22),
        dateMainAssociation: DateTime(1987, 5, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2002, 9, 1),
        role: RoleFidele.ancien,
        vulnerabilites: {VulnerabiliteFidele.troisiemeAge},
        idFamille: 'famille_akpo',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_010',
        fullName: 'Mireille Adjibi',
        gender: Gender.female,
        birthDate: DateTime(2005, 7, 14),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2020, 9, 4),
        phone: '+229 61000010',
        email: 'mireille.adjibi@example.com',
        address: 'Porto-Novo',
        dateNaissance: DateTime(2005, 7, 14),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2019, 6, 1),
        dateBapteme: DateTime(2020, 9, 4),
        dateMainAssociation: DateTime(2021, 2, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2015, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_adjibi',
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
      ),
      Member(
        id: 'fidele_011',
        fullName: 'David Adjibi',
        gender: Gender.male,
        birthDate: DateTime(2009, 11, 3),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2023, 8, 21),
        phone: '+229 61000011',
        address: 'Porto-Novo',
        dateNaissance: DateTime(2009, 11, 3),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2022, 5, 15),
        dateBapteme: DateTime(2023, 8, 21),
        dateMainAssociation: DateTime(2023, 10, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2017, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_adjibi',
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
      ),
      Member(
        id: 'fidele_012',
        fullName: 'Emmanuel Hounkpe',
        gender: Gender.male,
        birthDate: DateTime(1998, 11, 5),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2016, 4, 3),
        phone: '+229 61000012',
        email: 'emmanuel.hounkpe@example.com',
        address: 'Cotonou',
        dateNaissance: DateTime(1998, 11, 5),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2015, 8, 14),
        dateBapteme: DateTime(2016, 4, 3),
        dateMainAssociation: DateTime(2017, 6, 10),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2015, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_hounkpe',
        idAssembleeLocale: 'assemblee_cotonou_centre',
      ),
      Member(
        id: 'fidele_013',
        fullName: 'Prisca Hounkpe',
        gender: Gender.female,
        birthDate: DateTime(2002, 4, 16),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2019, 7, 22),
        phone: '+229 61000013',
        address: 'Cotonou',
        dateNaissance: DateTime(2002, 4, 16),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2018, 11, 10),
        dateBapteme: DateTime(2019, 7, 22),
        dateMainAssociation: DateTime(2020, 2, 2),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2012, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_hounkpe',
        idAssembleeLocale: 'assemblee_cotonou_centre',
      ),
      Member(
        id: 'fidele_014',
        fullName: 'Joel Gbeto',
        gender: Gender.male,
        birthDate: DateTime(1999, 10, 20),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2017, 6, 18),
        phone: '+229 61000014',
        email: 'joel.gbeto@example.com',
        address: 'Abomey-Calavi',
        dateNaissance: DateTime(1999, 10, 20),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2016, 4, 1),
        dateBapteme: DateTime(2017, 6, 18),
        dateMainAssociation: DateTime(2018, 1, 12),
        statut: StatutFidele.transfere,
        dateEntree: DateTime(2012, 2, 1),
        dateSortie: DateTime(2024, 1, 15),
        motifSortie: 'Transfert vers une autre assemblee',
        role: RoleFidele.membre,
        idFamille: 'famille_gbeto',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_015',
        fullName: 'Grace Gbeto',
        gender: Gender.female,
        birthDate: DateTime(2007, 2, 9),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2022, 3, 13),
        phone: '+229 61000015',
        address: 'Abomey-Calavi',
        dateNaissance: DateTime(2007, 2, 9),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2021, 11, 1),
        dateBapteme: DateTime(2022, 3, 13),
        dateMainAssociation: DateTime(2022, 8, 20),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2014, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_gbeto',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_016',
        fullName: 'Kevin Dossou',
        gender: Gender.male,
        birthDate: DateTime(2010, 3, 5),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2022, 8, 21),
        phone: '+229 61000016',
        address: 'Cotonou',
        dateNaissance: DateTime(2010, 3, 5),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2021, 4, 12),
        dateBapteme: DateTime(2022, 8, 21),
        dateMainAssociation: DateTime(2023, 1, 8),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2015, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_dossou',
        idAssembleeLocale: 'assemblee_agla',
      ),
      Member(
        id: 'fidele_017',
        fullName: 'Deborah Dossou',
        gender: Gender.female,
        birthDate: DateTime(2012, 8, 18),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2023, 7, 2),
        phone: '+229 61000017',
        address: 'Cotonou',
        dateNaissance: DateTime(2012, 8, 18),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2022, 9, 9),
        dateBapteme: DateTime(2023, 7, 2),
        dateMainAssociation: DateTime(2023, 11, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2017, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_dossou',
        idAssembleeLocale: 'assemblee_agla',
      ),
      Member(
        id: 'fidele_018',
        fullName: 'Martine Akpo',
        gender: Gender.female,
        birthDate: DateTime(1967, 4, 11),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1987, 10, 3),
        phone: '+229 61000018',
        email: 'martine.akpo@example.com',
        address: 'Abomey',
        dateNaissance: DateTime(1967, 4, 11),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1986, 5, 20),
        dateBapteme: DateTime(1987, 10, 3),
        dateMainAssociation: DateTime(1988, 6, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2002, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_akpo',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_019',
        fullName: 'Ines Akpo',
        gender: Gender.female,
        birthDate: DateTime(2004, 7, 22),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2021, 5, 16),
        phone: '+229 61000019',
        address: 'Abomey',
        dateNaissance: DateTime(2004, 7, 22),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2020, 3, 1),
        dateBapteme: DateTime(2021, 5, 16),
        dateMainAssociation: DateTime(2021, 9, 5),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2012, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_akpo',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_020',
        fullName: 'Yann Akpo',
        gender: Gender.male,
        birthDate: DateTime(2008, 1, 29),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2022, 9, 11),
        phone: '+229 61000020',
        address: 'Abomey',
        dateNaissance: DateTime(2008, 1, 29),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2021, 2, 14),
        dateBapteme: DateTime(2022, 9, 11),
        dateMainAssociation: DateTime(2023, 1, 6),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2015, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_akpo',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_021',
        fullName: 'Joel Kassa',
        gender: Gender.male,
        birthDate: DateTime(1988, 2, 17),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2008, 10, 19),
        phone: '+229 61000021',
        email: 'joel.kassa@example.com',
        address: 'Calavi',
        dateNaissance: DateTime(1988, 2, 17),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2007, 4, 22),
        dateBapteme: DateTime(2008, 10, 19),
        dateMainAssociation: DateTime(2009, 6, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2016, 3, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_kassa',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_022',
        fullName: 'Sandrine Kassa',
        gender: Gender.female,
        birthDate: DateTime(1990, 6, 2),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2010, 2, 14),
        phone: '+229 61000022',
        email: 'sandrine.kassa@example.com',
        address: 'Calavi',
        dateNaissance: DateTime(1990, 6, 2),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2009, 3, 10),
        dateBapteme: DateTime(2010, 2, 14),
        dateMainAssociation: DateTime(2011, 1, 5),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2016, 3, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_kassa',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_023',
        fullName: 'Eden Kassa',
        gender: Gender.female,
        birthDate: DateTime(2015, 12, 3),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2024, 4, 7),
        phone: '+229 61000023',
        address: 'Calavi',
        dateNaissance: DateTime(2015, 12, 3),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2023, 9, 18),
        dateBapteme: DateTime(2024, 4, 7),
        dateMainAssociation: DateTime(2024, 6, 2),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2022, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_kassa',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_024',
        fullName: 'Samuel Kassa',
        gender: Gender.male,
        birthDate: DateTime(2017, 4, 18),
        maritalStatus: MaritalStatus.single,
        phone: '+229 61000024',
        address: 'Calavi',
        dateNaissance: DateTime(2017, 4, 18),
        statutMatrimonial: StatutMatrimonial.celibataire,
        statut: StatutFidele.actif,
        dateEntree: DateTime(2022, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_kassa',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_025',
        fullName: 'Germain Ahouansou',
        gender: Gender.male,
        birthDate: DateTime(1958, 9, 9),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1981, 12, 14),
        phone: '+229 61000025',
        address: 'Ouidah',
        dateNaissance: DateTime(1958, 9, 9),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1980, 6, 1),
        dateBapteme: DateTime(1981, 12, 14),
        dateMainAssociation: DateTime(1983, 5, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2000, 1, 1),
        role: RoleFidele.diacre,
        vulnerabilites: {VulnerabiliteFidele.troisiemeAge},
        idFamille: 'famille_ahouansou',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_026',
        fullName: 'Bernadette Ahouansou',
        gender: Gender.female,
        birthDate: DateTime(1960, 5, 14),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1983, 3, 12),
        phone: '+229 61000026',
        address: 'Ouidah',
        dateNaissance: DateTime(1960, 5, 14),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1982, 4, 19),
        dateBapteme: DateTime(1983, 3, 12),
        dateMainAssociation: DateTime(1984, 6, 5),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2000, 1, 1),
        role: RoleFidele.diaconesse,
        vulnerabilites: {VulnerabiliteFidele.troisiemeAge},
        idFamille: 'famille_ahouansou',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_027',
        fullName: 'Patrick Ahouansou',
        gender: Gender.male,
        birthDate: DateTime(1992, 3, 1),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2010, 9, 5),
        phone: '+229 61000027',
        email: 'patrick.ahouansou@example.com',
        address: 'Ouidah',
        dateNaissance: DateTime(1992, 3, 1),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2009, 8, 15),
        dateBapteme: DateTime(2010, 9, 5),
        dateMainAssociation: DateTime(2011, 4, 9),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2012, 6, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_ahouansou',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_028',
        fullName: 'Christelle Ahouansou',
        gender: Gender.female,
        birthDate: DateTime(1995, 7, 27),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2014, 1, 19),
        phone: '+229 61000028',
        address: 'Ouidah',
        dateNaissance: DateTime(1995, 7, 27),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2013, 9, 1),
        dateBapteme: DateTime(2014, 1, 19),
        dateMainAssociation: DateTime(2014, 10, 2),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2013, 6, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_ahouansou',
        idAssembleeLocale: 'assemblee_ouidah_centre',
      ),
      Member(
        id: 'fidele_029',
        fullName: 'Victorine Azon',
        gender: Gender.female,
        birthDate: DateTime(1978, 12, 15),
        maritalStatus: MaritalStatus.widowed,
        baptismDate: DateTime(2000, 5, 21),
        phone: '+229 61000029',
        email: 'victorine.azon@example.com',
        address: 'Cotonou',
        dateNaissance: DateTime(1978, 12, 15),
        statutMatrimonial: StatutMatrimonial.veuve,
        dateConversion: DateTime(1999, 10, 10),
        dateBapteme: DateTime(2000, 5, 21),
        dateMainAssociation: DateTime(2001, 8, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2011, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.veuve},
        idFamille: 'famille_azon',
        idAssembleeLocale: 'assemblee_fidjrosse',
      ),
      Member(
        id: 'fidele_030',
        fullName: 'Pierre Azon',
        gender: Gender.male,
        birthDate: DateTime(2003, 5, 19),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2021, 2, 14),
        phone: '+229 61000030',
        address: 'Cotonou',
        dateNaissance: DateTime(2003, 5, 19),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2020, 6, 9),
        dateBapteme: DateTime(2021, 2, 14),
        dateMainAssociation: DateTime(2021, 9, 10),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2012, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.orphelin},
        idFamille: 'famille_azon',
        idAssembleeLocale: 'assemblee_fidjrosse',
      ),
      Member(
        id: 'fidele_031',
        fullName: 'Linda Azon',
        gender: Gender.female,
        birthDate: DateTime(2007, 9, 8),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2023, 6, 18),
        phone: '+229 61000031',
        address: 'Cotonou',
        dateNaissance: DateTime(2007, 9, 8),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2022, 11, 1),
        dateBapteme: DateTime(2023, 6, 18),
        dateMainAssociation: DateTime(2023, 10, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2015, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.orphelin},
        idFamille: 'famille_azon',
        idAssembleeLocale: 'assemblee_fidjrosse',
      ),
      Member(
        id: 'fidele_032',
        fullName: 'Serge Alabi',
        gender: Gender.male,
        birthDate: DateTime(1985, 10, 10),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2006, 5, 6),
        phone: '+229 61000032',
        address: 'Calavi',
        dateNaissance: DateTime(1985, 10, 10),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2004, 9, 15),
        dateBapteme: DateTime(2006, 5, 6),
        dateMainAssociation: DateTime(2007, 2, 2),
        statut: StatutFidele.inactif,
        dateEntree: DateTime(2016, 6, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_alabi',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_033',
        fullName: 'Ruth Alabi',
        gender: Gender.female,
        birthDate: DateTime(1987, 1, 7),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(2007, 6, 3),
        phone: '+229 61000033',
        address: 'Calavi',
        dateNaissance: DateTime(1987, 1, 7),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(2006, 9, 10),
        dateBapteme: DateTime(2007, 6, 3),
        dateMainAssociation: DateTime(2008, 4, 5),
        statut: StatutFidele.transfere,
        dateEntree: DateTime(2016, 6, 1),
        dateSortie: DateTime(2023, 10, 1),
        motifSortie: 'Demenagement a une autre ville',
        role: RoleFidele.membre,
        idFamille: 'famille_alabi',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_034',
        fullName: 'Daniel Alabi',
        gender: Gender.male,
        birthDate: DateTime(2012, 11, 26),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2023, 5, 14),
        phone: '+229 61000034',
        address: 'Calavi',
        dateNaissance: DateTime(2012, 11, 26),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2022, 10, 9),
        dateBapteme: DateTime(2023, 5, 14),
        dateMainAssociation: DateTime(2023, 9, 3),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2018, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_alabi',
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_035',
        fullName: 'Charles Mensah',
        gender: Gender.male,
        birthDate: DateTime(1974, 3, 9),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1995, 1, 8),
        phone: '+229 61000035',
        address: 'Godomey',
        dateNaissance: DateTime(1974, 3, 9),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1993, 7, 20),
        dateBapteme: DateTime(1995, 1, 8),
        dateMainAssociation: DateTime(1996, 6, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2009, 1, 1),
        role: RoleFidele.diacre,
        idFamille: 'famille_mensah',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_036',
        fullName: 'Gloria Mensah',
        gender: Gender.female,
        birthDate: DateTime(1976, 6, 19),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1996, 3, 3),
        phone: '+229 61000036',
        address: 'Godomey',
        dateNaissance: DateTime(1976, 6, 19),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1994, 9, 9),
        dateBapteme: DateTime(1996, 3, 3),
        dateMainAssociation: DateTime(1997, 4, 6),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2009, 1, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_mensah',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_037',
        fullName: 'Kossi Mensah',
        gender: Gender.male,
        birthDate: DateTime(2006, 8, 15),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2022, 9, 25),
        phone: '+229 61000037',
        address: 'Godomey',
        dateNaissance: DateTime(2006, 8, 15),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2021, 6, 20),
        dateBapteme: DateTime(2022, 9, 25),
        dateMainAssociation: DateTime(2023, 2, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2014, 9, 1),
        role: RoleFidele.membre,
        idFamille: 'famille_mensah',
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_038',
        fullName: 'Alice Boko',
        gender: Gender.female,
        birthDate: DateTime(2003, 2, 12),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2020, 6, 7),
        phone: '+229 61000038',
        address: 'Cotonou',
        dateNaissance: DateTime(2003, 2, 12),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2019, 5, 4),
        dateBapteme: DateTime(2020, 6, 7),
        dateMainAssociation: DateTime(2021, 1, 10),
        statut: StatutFidele.inactif,
        dateEntree: DateTime(2018, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.orphelin},
        idAssembleeLocale: 'assemblee_fidjrosse',
      ),
      Member(
        id: 'fidele_039',
        fullName: 'Marcel Degla',
        gender: Gender.male,
        birthDate: DateTime(2004, 12, 1),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2021, 11, 14),
        phone: '+229 61000039',
        address: 'Cotonou',
        dateNaissance: DateTime(2004, 12, 1),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2020, 8, 9),
        dateBapteme: DateTime(2021, 11, 14),
        dateMainAssociation: DateTime(2022, 4, 3),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2019, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.orphelin},
        idAssembleeLocale: 'assemblee_agla',
      ),
      Member(
        id: 'fidele_040',
        fullName: 'Lauriane Gbenou',
        gender: Gender.female,
        birthDate: DateTime(2008, 3, 21),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2023, 4, 30),
        phone: '+229 61000040',
        address: 'Calavi',
        dateNaissance: DateTime(2008, 3, 21),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2022, 9, 12),
        dateBapteme: DateTime(2023, 4, 30),
        dateMainAssociation: DateTime(2023, 9, 17),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2016, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.orphelin},
        idAssembleeLocale: 'assemblee_calavi_centre',
      ),
      Member(
        id: 'fidele_041',
        fullName: 'Edmond Houngue',
        gender: Gender.male,
        birthDate: DateTime(1962, 11, 23),
        maritalStatus: MaritalStatus.widowed,
        baptismDate: DateTime(1984, 7, 1),
        phone: '+229 61000041',
        address: 'Cotonou',
        dateNaissance: DateTime(1962, 11, 23),
        statutMatrimonial: StatutMatrimonial.veuf,
        dateConversion: DateTime(1983, 1, 1),
        dateBapteme: DateTime(1984, 7, 1),
        dateMainAssociation: DateTime(1985, 9, 1),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2007, 5, 1),
        role: RoleFidele.membre,
        vulnerabilites: {
          VulnerabiliteFidele.veuf,
          VulnerabiliteFidele.troisiemeAge,
        },
        idAssembleeLocale: 'assemblee_cotonou_centre',
      ),
      Member(
        id: 'fidele_042',
        fullName: 'Julien Loko',
        gender: Gender.male,
        birthDate: DateTime(1990, 1, 30),
        maritalStatus: MaritalStatus.single,
        baptismDate: DateTime(2010, 10, 10),
        phone: '+229 61000042',
        address: 'Porto-Novo',
        dateNaissance: DateTime(1990, 1, 30),
        statutMatrimonial: StatutMatrimonial.celibataire,
        dateConversion: DateTime(2009, 4, 15),
        dateBapteme: DateTime(2010, 10, 10),
        dateMainAssociation: DateTime(2011, 3, 12),
        statut: StatutFidele.actif,
        dateEntree: DateTime(2014, 9, 1),
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.handicape},
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
      ),
      Member(
        id: 'fidele_043',
        fullName: 'Carine Teko',
        gender: Gender.female,
        birthDate: DateTime(1995, 4, 3),
        maritalStatus: MaritalStatus.divorced,
        baptismDate: DateTime(2015, 2, 1),
        phone: '+229 61000043',
        address: 'Porto-Novo',
        dateNaissance: DateTime(1995, 4, 3),
        statutMatrimonial: StatutMatrimonial.separe,
        dateConversion: DateTime(2013, 6, 7),
        dateBapteme: DateTime(2015, 2, 1),
        dateMainAssociation: DateTime(2016, 3, 1),
        statut: StatutFidele.parti,
        dateEntree: DateTime(2017, 7, 1),
        dateSortie: DateTime(2024, 6, 10),
        motifSortie: 'Abandon de la foi',
        role: RoleFidele.membre,
        vulnerabilites: {VulnerabiliteFidele.handicape},
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
      ),
      Member(
        id: 'fidele_044',
        fullName: 'Paulin Adon',
        gender: Gender.male,
        birthDate: DateTime(1969, 9, 14),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1990, 1, 21),
        phone: '+229 61000044',
        address: 'Calavi',
        dateNaissance: DateTime(1969, 9, 14),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1988, 12, 4),
        dateBapteme: DateTime(1990, 1, 21),
        dateMainAssociation: DateTime(1991, 7, 1),
        statut: StatutFidele.decede,
        dateEntree: DateTime(2004, 9, 1),
        dateDeces: DateTime(2023, 12, 1),
        role: RoleFidele.membre,
        idAssembleeLocale: 'assemblee_akassato',
      ),
      Member(
        id: 'fidele_045',
        fullName: 'Elise Adon',
        gender: Gender.female,
        birthDate: DateTime(1972, 5, 25),
        maritalStatus: MaritalStatus.married,
        baptismDate: DateTime(1992, 8, 30),
        phone: '+229 61000045',
        address: 'Calavi',
        dateNaissance: DateTime(1972, 5, 25),
        statutMatrimonial: StatutMatrimonial.marie,
        dateConversion: DateTime(1991, 3, 1),
        dateBapteme: DateTime(1992, 8, 30),
        dateMainAssociation: DateTime(1993, 9, 12),
        statut: StatutFidele.decede,
        dateEntree: DateTime(2004, 9, 1),
        dateDeces: DateTime(2022, 8, 20),
        role: RoleFidele.membre,
        idAssembleeLocale: 'assemblee_akassato',
      ),
    ]);

    _familles.addAll([
      Famille(
        id: 'famille_adjibi',
        nom: 'Famille ADJIBI',
        idEpoux: 'fidele_001',
        idEpouse: 'fidele_002',
        idsEnfants: ['fidele_010', 'fidele_011'],
      ),
      Famille(
        id: 'famille_hounkpe',
        nom: 'Famille HOUNKPE',
        idEpoux: 'fidele_003',
        idEpouse: 'fidele_004',
        idsEnfants: ['fidele_012', 'fidele_013'],
      ),
      Famille(
        id: 'famille_gbeto',
        nom: 'Famille GBETO',
        idEpoux: 'fidele_005',
        idEpouse: 'fidele_006',
        idsEnfants: ['fidele_014', 'fidele_015'],
      ),
      Famille(
        id: 'famille_dossou',
        nom: 'Famille DOSSOU',
        idEpoux: 'fidele_007',
        idEpouse: 'fidele_008',
        idsEnfants: ['fidele_016', 'fidele_017'],
      ),
      Famille(
        id: 'famille_akpo',
        nom: 'Famille AKPO',
        idEpoux: 'fidele_009',
        idEpouse: 'fidele_018',
        idsEnfants: ['fidele_019', 'fidele_020'],
      ),
      Famille(
        id: 'famille_kassa',
        nom: 'Famille KASSA',
        idEpoux: 'fidele_021',
        idEpouse: 'fidele_022',
        idsEnfants: ['fidele_023', 'fidele_024'],
      ),
      Famille(
        id: 'famille_ahouansou',
        nom: 'Famille AHOUANSOU',
        idEpoux: 'fidele_025',
        idEpouse: 'fidele_026',
        idsEnfants: ['fidele_027', 'fidele_028'],
      ),
      Famille(
        id: 'famille_azon',
        nom: 'Famille AZON',
        idEpouse: 'fidele_029',
        idsEnfants: ['fidele_030', 'fidele_031'],
      ),
      Famille(
        id: 'famille_alabi',
        nom: 'Famille ALABI',
        idEpoux: 'fidele_032',
        idEpouse: 'fidele_033',
        idsEnfants: ['fidele_034'],
      ),
      Famille(
        id: 'famille_mensah',
        nom: 'Famille MENSAH',
        idEpoux: 'fidele_035',
        idEpouse: 'fidele_036',
        idsEnfants: ['fidele_037'],
      ),
    ]);
    _programs.addAll([
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 3, 2),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - serie Foi et service',
        observations: 'Mettre en avant les groupes famille',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_007',
          'fidele_035',
        ],
        nombreHommes: 48,
        nombreFemmes: 65,
        nombreGarcons: 18,
        nombreFilles: 22,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.ecoleDuDimanche,
        date: DateTime(2025, 3, 2),
        location: 'Salle des enfants',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Ecole du dimanche - classes regroupees',
        observations: 'Chants appris pour Paques',
        participantIds: const [
          'fidele_015',
          'fidele_017',
          'fidele_023',
          'fidele_034',
        ],
        nombreClassesEcoleDuDimanche: 4,
        nombreMoniteursHommes: 2,
        nombreMonitricesFemmes: 3,
        derniereLeconEcoleDuDimanche: 'La foi et l obedience',
        nombreHommes: 0,
        nombreFemmes: 0,
        nombreGarcons: 32,
        nombreFilles: 35,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.sainteCene,
        date: DateTime(2025, 3, 2),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Service de sainte cene',
        observations: 'Distribution en fin de culte',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 47,
        nombreFemmes: 63,
        nombreGarcons: 17,
        nombreFilles: 21,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.visite,
        date: DateTime(2025, 3, 3),
        location: 'Porto-Novo - famille Adjibi',
        idAssembleeLocale: 'assemblee_porto_novo_koutongou',
        description: 'Visite pastorale',
        typeVisite: TypeVisite.fidele,
        participantIds: const [
          'fidele_001',
          'fidele_002',
        ],
        nombreHommes: 1,
        nombreFemmes: 1,
        nombreGarcons: 0,
        nombreFilles: 0,
        compteRenduVisite:
            'Visite pastorale pour soutenir la famille. Priere avec les parents et encouragement sur la perseverance. La famille a demande une presence au prochain culte.',
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.reunionPriere,
        date: DateTime(2025, 3, 4),
        location: 'Temple central - salle de priere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Reunion de priere du mardi',
        observations: 'Intercession pour les malades',
        participantIds: const [
          'fidele_003',
          'fidele_007',
          'fidele_012',
        ],
        nombreHommes: 22,
        nombreFemmes: 30,
        nombreGarcons: 6,
        nombreFilles: 8,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.visite,
        date: DateTime(2025, 3, 7),
        location: 'Mairie d Abomey-Calavi',
        idAssembleeLocale: 'assemblee_calavi_centre',
        description: 'Visite aux autorites locales',
        typeVisite: TypeVisite.autorite,
        participantIds: const [
          'fidele_003',
          'fidele_021',
          'fidele_035',
        ],
        nombreHommes: 2,
        nombreFemmes: 1,
        nombreGarcons: 0,
        nombreFilles: 0,
        compteRenduVisite:
            'Rencontre avec le secretaire general pour presenter les actions sociales. Bonne ecoute et promesse de faciliter l autorisation pour la prochaine croisade. Suivi a faire par courrier.',
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.evangelisationPorteAPorte,
        date: DateTime(2025, 3, 8),
        location: 'Quartier Tokan',
        idAssembleeLocale: 'assemblee_calavi_centre',
        description: 'Porte a porte en petits groupes',
        observations: 'Distribution de tracts et priere',
        participantIds: const [
          'fidele_012',
          'fidele_015',
          'fidele_021',
          'fidele_039',
        ],
        nombreHommes: 15,
        nombreFemmes: 18,
        nombreGarcons: 5,
        nombreFilles: 6,
        conversionsHommes: 2,
        conversionsFemmes: 2,
        conversionsGarcons: 1,
        conversionsFilles: 1,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 3, 9),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - temoignages',
        observations: 'Mise en avant des jeunes convertis',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_021',
          'fidele_035',
        ],
        nombreHommes: 50,
        nombreFemmes: 66,
        nombreGarcons: 20,
        nombreFilles: 23,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.mainsAssociation,
        date: DateTime(2025, 3, 9),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Mains d association de trois fideles',
        observations: 'Suivi pastoral programme',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_007',
        ],
        nombreHommes: 8,
        nombreFemmes: 12,
        nombreGarcons: 2,
        nombreFilles: 3,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.reunionPriere,
        date: DateTime(2025, 3, 11),
        location: 'Temple central - salle de priere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Reunion de priere du mardi',
        observations: 'Focus sur la consolidation des nouveaux',
        participantIds: const [
          'fidele_003',
          'fidele_007',
          'fidele_012',
        ],
        nombreHommes: 20,
        nombreFemmes: 28,
        nombreGarcons: 5,
        nombreFilles: 7,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.discipline,
        date: DateTime(2025, 3, 12),
        location: 'Salle des anciens',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Seance de discipline et accompagnement',
        observations: 'Plan de suivi sur 3 mois',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_007',
        ],
        nombreHommes: 6,
        nombreFemmes: 4,
        nombreGarcons: 0,
        nombreFilles: 0,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.evangelisationMasse,
        date: DateTime(2025, 3, 15),
        location: 'Marche de Calavi',
        idAssembleeLocale: 'assemblee_calavi_centre',
        description: 'Campagne d evangelisation de masse',
        observations: 'Sono mobile et coordination logistique',
        participantIds: const [
          'fidele_003',
          'fidele_012',
          'fidele_015',
          'fidele_021',
        ],
        nombreHommes: 60,
        nombreFemmes: 70,
        nombreGarcons: 22,
        nombreFilles: 25,
        conversionsHommes: 8,
        conversionsFemmes: 9,
        conversionsGarcons: 3,
        conversionsFilles: 4,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 3, 16),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - serie Foi et service',
        observations: 'Appel a la formation des moniteurs',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 52,
        nombreFemmes: 70,
        nombreGarcons: 21,
        nombreFilles: 24,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.ecoleDuDimanche,
        date: DateTime(2025, 3, 16),
        location: 'Salle des enfants',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Ecole du dimanche - ateliers',
        observations: 'Preparation d un sketch biblique',
        participantIds: const [
          'fidele_015',
          'fidele_017',
          'fidele_023',
          'fidele_034',
        ],
        nombreClassesEcoleDuDimanche: 4,
        nombreMoniteursHommes: 2,
        nombreMonitricesFemmes: 3,
        derniereLeconEcoleDuDimanche: 'La vie de Joseph',
        nombreHommes: 0,
        nombreFemmes: 0,
        nombreGarcons: 30,
        nombreFilles: 32,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.visite,
        date: DateTime(2025, 3, 17),
        location: 'ONG Lumiere du Sud',
        idAssembleeLocale: 'assemblee_agla',
        description: 'Visite partenaire',
        typeVisite: TypeVisite.partenaire,
        participantIds: const [
          'fidele_007',
          'fidele_012',
          'fidele_021',
        ],
        nombreHommes: 2,
        nombreFemmes: 1,
        nombreGarcons: 0,
        nombreFilles: 0,
        compteRenduVisite:
            'Echange sur le projet alphab. Le partenaire propose un appui en manuels et en formateurs. Rendez-vous confirme pour une session en avril.',
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.reunionPriere,
        date: DateTime(2025, 3, 18),
        location: 'Temple central - salle de priere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Reunion de priere du mardi',
        observations: 'Priere pour les evangelisations a venir',
        participantIds: const [
          'fidele_003',
          'fidele_007',
          'fidele_012',
        ],
        nombreHommes: 24,
        nombreFemmes: 32,
        nombreGarcons: 6,
        nombreFilles: 8,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.baptemes,
        date: DateTime(2025, 3, 22),
        location: 'Temple central - baptistere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Service de baptemes de printemps',
        observations: 'Certificats remis apres temoignages',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_007',
        ],
        nombreHommes: 12,
        nombreFemmes: 15,
        nombreGarcons: 5,
        nombreFilles: 4,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 3, 23),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - preparation Paques',
        observations: 'Presentation du programme de Paques',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_021',
          'fidele_035',
        ],
        nombreHommes: 54,
        nombreFemmes: 72,
        nombreGarcons: 22,
        nombreFilles: 25,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.visite,
        date: DateTime(2025, 3, 24),
        location: 'Assemblee soeur de Godomey',
        idAssembleeLocale: 'assemblee_calavi_centre',
        description: 'Visite fraternelle',
        typeVisite: TypeVisite.autreAssemblee,
        participantIds: const [
          'fidele_003',
          'fidele_035',
          'fidele_038',
          'fidele_039',
        ],
        nombreHommes: 2,
        nombreFemmes: 2,
        nombreGarcons: 0,
        nombreFilles: 0,
        compteRenduVisite:
            'Partage fraternel et priere pour leurs projets de construction. Invitation reciproque pour la veillee du mois prochain. Echange de contacts des responsables jeunesse.',
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.evangelisationPorteAPorte,
        date: DateTime(2025, 3, 29),
        location: 'Quartier Kindonou',
        idAssembleeLocale: 'assemblee_agla',
        description: 'Sortie porte a porte',
        observations: 'Equipe divisee en trois parcours',
        participantIds: const [
          'fidele_012',
          'fidele_015',
          'fidele_021',
          'fidele_039',
        ],
        nombreHommes: 14,
        nombreFemmes: 16,
        nombreGarcons: 4,
        nombreFilles: 5,
        conversionsHommes: 1,
        conversionsFemmes: 2,
        conversionsGarcons: 1,
        conversionsFilles: 1,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 3, 30),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - louange et mission',
        observations: 'Collecte speciale pour mission rurale',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 55,
        nombreFemmes: 74,
        nombreGarcons: 23,
        nombreFilles: 26,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.ecoleDuDimanche,
        date: DateTime(2025, 3, 30),
        location: 'Salle des enfants',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Ecole du dimanche - dimanche creatif',
        observations: 'Chant final repete avec la chorale jeunesse',
        participantIds: const [
          'fidele_015',
          'fidele_017',
          'fidele_023',
          'fidele_034',
        ],
        nombreClassesEcoleDuDimanche: 5,
        nombreMoniteursHommes: 2,
        nombreMonitricesFemmes: 3,
        derniereLeconEcoleDuDimanche: 'La priere selon Jesus',
        nombreHommes: 0,
        nombreFemmes: 0,
        nombreGarcons: 33,
        nombreFilles: 34,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.visite,
        date: DateTime(2025, 4, 2),
        location: 'Cotonou - chez soeur Victorine',
        idAssembleeLocale: 'assemblee_fidjrosse',
        description: 'Visite a domicile',
        typeVisite: TypeVisite.fidele,
        participantIds: const [
          'fidele_002',
          'fidele_029',
          'fidele_040',
        ],
        nombreHommes: 1,
        nombreFemmes: 2,
        nombreGarcons: 0,
        nombreFilles: 0,
        compteRenduVisite:
            'Soutien moral apres une hospitalisation. Lecture et priere ensemble. Rendez-vous pris pour assurer le transport vers le culte dimanche.',
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 4, 6),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - debut mois d avril',
        observations: 'Mise en avant de la chorale mixte',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_007',
          'fidele_035',
        ],
        nombreHommes: 58,
        nombreFemmes: 76,
        nombreGarcons: 24,
        nombreFilles: 27,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.reunionPriere,
        date: DateTime(2025, 4, 8),
        location: 'Temple central - salle de priere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Reunion de priere du mardi',
        observations: 'Priere pour les examens des jeunes',
        participantIds: const [
          'fidele_003',
          'fidele_007',
          'fidele_012',
        ],
        nombreHommes: 23,
        nombreFemmes: 31,
        nombreGarcons: 5,
        nombreFilles: 7,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.evangelisationMasse,
        date: DateTime(2025, 4, 12),
        location: 'Place publique d Abomey-Calavi',
        idAssembleeLocale: 'assemblee_calavi_centre',
        description: 'Campagne d evangelisation regionale',
        observations: 'Coordination avec les partenaires locaux',
        participantIds: const [
          'fidele_003',
          'fidele_012',
          'fidele_015',
          'fidele_021',
        ],
        nombreHommes: 58,
        nombreFemmes: 68,
        nombreGarcons: 20,
        nombreFilles: 24,
        conversionsHommes: 6,
        conversionsFemmes: 7,
        conversionsGarcons: 3,
        conversionsFilles: 4,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 4, 13),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - engagement communautaire',
        observations: 'Presentation des nouveaux moniteurs',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 60,
        nombreFemmes: 78,
        nombreGarcons: 25,
        nombreFilles: 28,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.ecoleDuDimanche,
        date: DateTime(2025, 4, 13),
        location: 'Salle des enfants',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Ecole du dimanche - journee familles',
        observations: 'Repetition pour la fete des enfants',
        participantIds: const [
          'fidele_015',
          'fidele_017',
          'fidele_023',
          'fidele_034',
        ],
        nombreClassesEcoleDuDimanche: 5,
        nombreMoniteursHommes: 3,
        nombreMonitricesFemmes: 3,
        derniereLeconEcoleDuDimanche: 'Les paraboles du Royaume',
        nombreHommes: 0,
        nombreFemmes: 0,
        nombreGarcons: 35,
        nombreFilles: 36,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.mainsAssociation,
        date: DateTime(2025, 4, 13),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Mains d association et engagement',
        observations: 'Suivi des nouveaux engagees',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_007',
        ],
        nombreHommes: 9,
        nombreFemmes: 13,
        nombreGarcons: 3,
        nombreFilles: 4,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.visite,
        date: DateTime(2025, 4, 16),
        location: 'Association Jeunes Solidaires',
        idAssembleeLocale: 'assemblee_agla',
        description: 'Visite partenaire',
        typeVisite: TypeVisite.autre,
        participantIds: const [
          'fidele_007',
          'fidele_012',
          'fidele_021',
          'fidele_035',
        ],
        nombreHommes: 2,
        nombreFemmes: 2,
        nombreGarcons: 0,
        nombreFilles: 0,
        compteRenduVisite:
            'Rencontre pour planifier une action sociale conjointe. Les responsables proposent d offrir des kits scolaires. Retour attendu sur le budget detaille.',
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.mariage,
        date: DateTime(2025, 4, 18),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_akassato',
        description: 'Mariage de la famille Kassa',
        observations: 'Cadeaux remis par les departements',
        participantIds: const [
          'fidele_001',
          'fidele_022',
          'fidele_023',
          'fidele_024',
        ],
        nombreHommes: 22,
        nombreFemmes: 32,
        nombreGarcons: 4,
        nombreFilles: 6,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.evangelisationPorteAPorte,
        date: DateTime(2025, 4, 19),
        location: 'Quartier Vedoko',
        idAssembleeLocale: 'assemblee_fidjrosse',
        description: 'Evangelisation porte a porte',
        observations: 'Equipe jeunesse mobilisee',
        participantIds: const [
          'fidele_012',
          'fidele_015',
          'fidele_021',
          'fidele_039',
        ],
        nombreHommes: 16,
        nombreFemmes: 19,
        nombreGarcons: 5,
        nombreFilles: 5,
        conversionsHommes: 2,
        conversionsFemmes: 2,
        conversionsGarcons: 1,
        conversionsFilles: 1,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.baptemes,
        date: DateTime(2025, 4, 20),
        location: 'Temple central - baptistere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Service de baptemes Paques',
        observations: 'Accompagnement par les moniteurs jeunesse',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_007',
        ],
        nombreHommes: 14,
        nombreFemmes: 20,
        nombreGarcons: 5,
        nombreFilles: 6,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 4, 20),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte de Paques',
        observations: 'Celebration avec chorale enfants et jeunesse',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 63,
        nombreFemmes: 80,
        nombreGarcons: 26,
        nombreFilles: 30,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.reunionPriere,
        date: DateTime(2025, 4, 22),
        location: 'Temple central - salle de priere',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Reunion de priere du mardi',
        observations: 'Priere pour les familles en deuil',
        participantIds: const [
          'fidele_003',
          'fidele_007',
          'fidele_012',
        ],
        nombreHommes: 21,
        nombreFemmes: 29,
        nombreGarcons: 4,
        nombreFilles: 6,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.evangelisationMasse,
        date: DateTime(2025, 4, 26),
        location: 'Stade de quartier',
        idAssembleeLocale: 'assemblee_agla',
        description: 'Grande soiree evangelisation',
        observations: 'Coordination avec l equipe securite',
        participantIds: const [
          'fidele_003',
          'fidele_012',
          'fidele_015',
          'fidele_021',
        ],
        nombreHommes: 70,
        nombreFemmes: 78,
        nombreGarcons: 24,
        nombreFilles: 28,
        conversionsHommes: 9,
        conversionsFemmes: 10,
        conversionsGarcons: 4,
        conversionsFilles: 5,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.culte,
        date: DateTime(2025, 4, 27),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Culte dominical - fin de mois',
        observations: 'Remerciements aux equipes evangelisation',
        participantIds: const [
          'fidele_001',
          'fidele_002',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 65,
        nombreFemmes: 82,
        nombreGarcons: 27,
        nombreFilles: 31,
      ),
      Program(
        id: _uuid.v4(),
        type: TypeProgramme.sainteCene,
        date: DateTime(2025, 4, 27),
        location: 'Temple central',
        idAssembleeLocale: 'assemblee_cotonou_centre',
        description: 'Service de sainte cene',
        observations: 'Moments de reconnaissance et benediction',
        participantIds: const [
          'fidele_001',
          'fidele_003',
          'fidele_035',
        ],
        nombreHommes: 64,
        nombreFemmes: 80,
        nombreGarcons: 27,
        nombreFilles: 30,
      ),
    ]);

    _entries.addAll([
      AccountingEntry(
        id: _uuid.v4(),
        date: DateTime.now().subtract(const Duration(days: 3)),
        amount: 150000,
        type: AccountingType.income,
        category: 'Dimes',
        description: 'Collecte principale du culte',
        paymentMethod: 'Especes',
      ),
      AccountingEntry(
        id: _uuid.v4(),
        date: DateTime.now().subtract(const Duration(days: 2)),
        amount: 40000,
        type: AccountingType.expense,
        category: 'Facture electricite',
        description: 'Reglement facture SBEE',
        paymentMethod: 'Virement',
      ),
      AccountingEntry(
        id: _uuid.v4(),
        date: DateTime.now().subtract(const Duration(days: 15)),
        amount: 90000,
        type: AccountingType.income,
        category: 'Offrandes ordinaires',
        description: 'Culte jeunesse',
        paymentMethod: 'Especes',
      ),
      AccountingEntry(
        id: _uuid.v4(),
        date: DateTime.now().subtract(const Duration(days: 20)),
        amount: 25000,
        type: AccountingType.expense,
        category: 'Achat de chaises',
        description: 'Achat pour salle des enfants',
        paymentMethod: 'Mobile money',
      ),
    ]);
  }

  @override
  Future<void> addAccountingEntry(AccountingEntry entry) async {
    _entries.add(entry);
  }

  @override
  Future<void> addMember(Member member) async {
    _members.add(member);
  }

  @override
  Future<void> addProgram(Program program) async {
    _programs.add(program);
  }

  @override
  Future<void> deleteAccountingEntry(String id) async {
    _entries.removeWhere((e) => e.id == id);
  }

  @override
  Future<void> deleteMember(String id) async {
    _members.removeWhere((m) => m.id == id);
    for (var i = 0; i < _programs.length; i++) {
      final program = _programs[i];
      _programs[i] = program.copyWith(
        participantIds: program.participantIds.where((pid) => pid != id).toList(),
      );
    }
  }

  @override
  Future<void> deleteProgram(String id) async {
    _programs.removeWhere((p) => p.id == id);
  }

  @override
  Future<List<AccountingEntry>> getAccountingEntries() async {
    return List<AccountingEntry>.unmodifiable(_entries);
  }

  @override
  Future<List<Member>> getMembers() async {
    return List<Member>.unmodifiable(_members);
  }

  @override
  Future<List<Program>> getPrograms() async {
    return List<Program>.unmodifiable(_programs);
  }

  @override
  Future<void> updateAccountingEntry(AccountingEntry entry) async {
    _entries
      ..removeWhere((e) => e.id == entry.id)
      ..add(entry);
  }

  @override
  Future<void> updateMember(Member member) async {
    _members
      ..removeWhere((m) => m.id == member.id)
      ..add(member);
  }

  @override
  Future<void> updateProgram(Program program) async {
    _programs
      ..removeWhere((p) => p.id == program.id)
      ..add(program);
  }

  @override
  Future<List<CompteComptable>> getComptesComptables() async {
    return _comptesComptables;
  }

  @override
  Future<List<JournalComptable>> getJournauxComptables() async {
    return _journauxComptables;
  }

  @override
  Future<List<CentreAnalytique>> getCentresAnalytiques() async {
    return _centresAnalytiques;
  }

  @override
  Future<List<Tiers>> getTiers() async {
    return _tiers;
  }

  @override
  Future<List<EcritureComptable>> getEcrituresComptables() async {
    return _ecrituresComptables;
  }
}
