import 'package:intl/intl.dart';

enum Gender { male, female }

enum MaritalStatus { single, married, divorced, widowed }

enum ProgramType {
  wedding,
  baptism,
  communion,
  evangelization,
  prayer,
  seminar,
  vigil,
  conference,
  youthRetreat,
}

enum AccountingType { income, expense }

const genderLabels = {Gender.male: 'Homme', Gender.female: 'Femme'};

const maritalStatusLabels = {
  MaritalStatus.single: 'Celibataire',
  MaritalStatus.married: 'Marie',
  MaritalStatus.divorced: 'Divorce',
  MaritalStatus.widowed: 'Veuf/Veuve',
};

const programTypeLabels = {
  ProgramType.wedding: 'Mariage',
  ProgramType.baptism: 'Bapteme',
  ProgramType.communion: 'Sainte cene',
  ProgramType.evangelization: 'Evangelisation',
  ProgramType.prayer: 'Priere',
  ProgramType.seminar: 'Seminaire',
  ProgramType.vigil: 'Veillee',
  ProgramType.conference: 'Conference',
  ProgramType.youthRetreat: 'Retraite',
};

const accountingTypeLabels = {
  AccountingType.income: 'Recette',
  AccountingType.expense: 'Depense',
};

const List<String> paymentMethods = [
  'Especes',
  'Virement',
  'Mobile money',
  'Cheque',
  'Carte bancaire',
];

final dateFormatter = DateFormat('dd/MM/yyyy');
final monthFormatter = DateFormat('MMM yyyy');
final currencyFormatter = NumberFormat.currency(
  locale: 'fr_FR',
  symbol: 'FCFA',
  decimalDigits: 0,
);

const List<String> incomeCategories = [
  'Dimes',
  'Offrandes ordinaires',
  'Offrandes speciales',
  'Offrandes de reconnaissance',
  'Offrandes pour le chantier',
  'Cotisations mensuelles des fideles',
  'Voeux accomplis en argent',
  'Premices',
  'Dons spontane des membres',
  'Dons en nature revendus',
  'Dons via mobile money',
  'Dons des visiteurs',
  'Dons des anciens de l\'eglise',
  'Dons du pasteur',
  'Collectes lors des croisades',
  'Collectes pour instruments de musique',
  'Collectes pour achat de bancs',
  'Vente de CD ou DVD',
  'Vente de brochures',
  'Vente de tenues d\'eglise',
  'Vente de gadgets',
  'Vente de repas lors des veillees',
  'Vente de boissons pour retraites',
  'Participation financiere aux campagnes',
  'Participation aux conferences',
  'Droits inscription formation biblique',
  'Vente de livres chretiens',
  'Vente d\'huile d\'onction',
  'Contribution pour le pasteur',
  'Aide pour orphelins ou veuves',
  'Contribution achat de terrain',
  'Collecte decoration du temple',
  'Parrainage d\'evenement',
  'Tickets de tombola ou soutien',
  'Organisation de kermesse',
  'Organisation de concert gospel',
  'Location de salle ou tentes',
  'Soutien d\'eglise mere ou soeurs',
  'Subvention regionale ou district',
  'Revenus activites agricoles',
  'Revenus production artisanale',
  'Revenus stand alimentaire',
  'Dons anonymes ou diaspora',
  'Vente de pagnes d\'eglise',
  'Vente de calendriers ou journaux',
  'Campagne de levee de fonds',
  'Financement participatif en ligne',
  'Dons par transfert bancaire',
  'Paiement de promesses anciennes',
  'Offrande anniversaire ou fete',
  'Collecte en ligne pendant live',
  'Vente de billets de seminaire ou retraite',
  'Produits derives d\'evenement',
  'Revenus emission radio ou tv',
  'Parrainage programme audiovisuel',
  'Collecte pour obseques',
  'Heritage ou vente de terrain',
  'Dons sponsors locaux',
  'Contribution pour eclairage ou video projecteur',
  'Revenus formations internes',
  'Retours d\'investissement micro-projet',
  'Dons a la chorale ou equipe technique',
  'Participation a un jeune collectif',
  'Soutien departement enfance ou jeunesse',
  'Revenus location de materiel',
  'Dons souvenirs defunt',
  'Dons anciens membres revenus',
  'Dons pour sonorisation',
  'Dons equipements multimedia',
  'Vente supports USB de preches',
  'Vente cle USB de documents',
  'Vente vin et pain sainte cene',
  'Vente affiches evangelisation',
  'Contribution pour generateur',
  'Contribution pour creusage de puits',
  'Dons pour mission rurale',
  'Dons pour mission etrangere',
  'Soutien eglise jumele a l etranger',
  'Partenariat strategique finance',
  'Remboursement fournisseur',
  'Subvention nationale ou region',
  'Revenus activites agricoles locales',
  'Revenus production artisanale locale',
  'Revenus stand alimentaire evenement',
  'Vente tickets de soutien',
  'Campagne levee de fonds locale',
  'Collecte nouvel an Paques Noel',
  'Collecte anniversaire eglise',
  'Collecte anniversaire pasteur',
  'Collecte en ligne live',
  'Revenus emission radio',
  'Revenus emission tv',
  'Parrainage programme audiovisuel',
  'Heritage ou donation terrain',
  'Dons sponsors locaux',
  'Dons diaspora',
  'Contribution cadres ou commercants',
  'Contribution enseignants ou eleves',
  'Contribution visiteurs reguliers',
  'Retours investissement micro projet',
  'Vente tickets seminaire ou retraite',
  'Paiement promesses anciennes',
  'Offrande anniversaire personnel',
  'Offrande anniversaire de mariage',
  'Dons pour eclairage du temple',
  'Contribution pour rideaux',
  'Contribution pour video projecteur',
  'Contribution pour ecran geant',
  'Revenus formations internes',
  'Soutien mairie locale ou autorites',
  'Paiement de voeux par SMS',
  'Dons en ligne mobile money',
  'Kermesse ou concert gospel',
  'Parrainage entreprises locales',
];

const List<String> expenseCategories = [
  'Loyer du lieu de culte',
  'Achat de chaises',
  'Achat de bancs',
  'Achat de ventilateurs',
  'Achat de climatiseurs',
  'Facture electricite',
  'Facture eau',
  'Achat de projecteur',
  'Achat d ecran geant',
  'Reparation de materiel',
  'Achat de micros',
  'Achat de cables',
  'Achat de batteries sono',
  'Achat de baffles',
  'Impression de brochures',
  'Impression d affiches',
  'Impression de livrets de chants',
  'Impression de recus',
  'Impression papiers a en-tete',
  'Achat de nappes et rideaux',
  'Achat materiel de decoration',
  'Achat de bougies',
  'Achat d huile d onction',
  'Achat de calices',
  'Achat de vin et pain sainte cene',
  'Achat de balais et serpillieres',
  'Achat de detergents',
  'Reparations plomberie',
  'Reparations electricite',
  'Reparations toiture',
  'Achat mobilier de bureau',
  'Achat d ordinateur',
  'Achat d imprimante',
  'Achat de logiciels',
  'Abonnement internet',
  'Abonnement logiciel de gestion',
  'Achat d extincteur',
  'Prime ou indemnites pasteur',
  'Indemnites des anciens',
  'Prime equipe technique',
  'Prime chorale',
  'Prime equipe entretien',
  'Transport du pasteur',
  'Transport membres pour seminaire',
  'Hebergement d invites',
  'Restauration des invites',
  'Frais participation convention',
  'Frais deplacement interregional',
  'Achat de carburant',
  'Achat de generateur',
  'Carburant pour generateur',
  'Location de tentes',
  'Location de chaises',
  'Location de baches',
  'Location de podium',
  'Location materiel sonorisation',
  'Location minibus',
  'Transport des instruments',
  'Achat nourriture pour evenements',
  'Achat boissons pour retraites',
  'Organisation de croisades',
  'Organisation de veillees',
  'Organisation de retraites spirituelles',
  'Organisation de seminaires',
  'Organisation de conferences',
  'Decorations evenementielles',
  'Achat badges participants',
  'Impression de tickets',
  'Achat de pagnes pour evenements',
  'Achat de tenues uniformes',
  'Soutien pasteur malade',
  'Soutien membre en deuil',
  'Soutien veuve ou orphelin',
  'Aide sociale locale',
  'Paiement honoraires conferenciers',
  'Frais de securite',
  'Frais de nettoyage',
  'Frais de sonorisation',
  'Entretien du temple',
  'Renovation du toit',
  'Peinture du batiment',
  'Rehabilitation des murs',
  'Carrelage du sol',
  'Achat fer a beton',
  'Achat de sable',
  'Achat de ciment',
  'Achat de planches',
  'Achat de vitres',
  'Pose de toiture',
  'Travaux de maconnerie',
  'Travaux de plomberie',
  'Travaux d electricite',
  'Amenagement de la cour',
  'Creation de toilettes',
  'Construction batiment annexe',
  'Construction bureau pastoral',
  'Construction classe ecole biblique',
  'Pose de portails',
  'Amenagement du parking',
  'Achat lampes exterieures',
  'Installation panneaux solaires',
  'Assurance du batiment',
  'Paiement taxes locales',
  'Achat de drapeaux',
  'Achat materiel de scene',
  'Achat de camera ou accessoires',
  'Abonnement plateformes en ligne',
  'Diffusion radio ou television',
  'Achat espace publicitaire',
  'Sponsoring emission chretienne',
  'Creation de site internet',
  'Entretien du site web',
  'Achat nom de domaine',
  'Achat hebergement web',
  'Paiement developpeur web',
  'Impression cartes invitation',
  'Impression certificats bapteme',
  'Achat papier stylos dossiers',
  'Achat cartouches encre',
  'Achat timbres et enveloppes',
  'Frais postaux',
  'Transport visite membres',
  'Transport mission evangelisation',
  'Frais mission etrangere',
  'Aide financiere a une autre eglise',
  'Soutien assemblees en difficulte',
  'Dons a l eglise mere ou district',
  'Cotisations nationales',
  'Frais de secretariat',
  'Honoraires comptables',
  'Audit des finances',
  'Remboursement de dettes',
  'Avances a rembourser',
  'Versement au siege national',
  'Contribution fonds urgence',
  'Appui jeunes en formation',
  'Appui projets des fideles',
  'Panneaux signaletiques',
  'Achat livres pour bibliotheque',
  'Abonnement revues chretiennes',
  'Recompense concours biblique',
  'Soutien personnes vulnerables',
  'Achat fournitures bureau diverses',
  'Frais hebergement mission',
  'Frais restauration mission',
  'Frais transport mission',
  'Location salle reunion',
  'Achat supports publicitaires',
  'Production audiovisuelle',
  'Maintenance equipements multimedia',
  'Assurance vehicule ou materiel',
  'Frais banque ou commissions',
  'Frais de securite evenementielle',
  'Prime volontaires evenement',
  'Frais nettoyage post evenement',
  'Achat gilets protocole',
  'Frais de formation interne',
  'Frais visa mission etrangere',
  'Achat kits evangelisation',
  'Dons solidarite locale',
  'Cotisation district ou region',
  'Contribution nationale urgences',
  'Depenses entretien parking',
  'Depenses amenagement jardin',
  'Reparations climatisation',
  'Reparations sonorisation',
  'Mise a niveau electricite',
  'Achat onduleur ou batteries',
  'Depenses diffusion en ligne',
  'Location minibus fideles',
  'Location camion pour instruments',
  'Soutien ecole chretienne locale',
  'Paiement honoraires experts',
  'Audit externe finances',
  'Frais postaux et timbres',
  'Achat enveloppes ou dossiers',
  'Impression cartes et certificats',
  'Travaux extension temple',
  'Equipements acces handicap',
  'Frais archivage documents',
  'Licences logicielles diverses',
  'Formations comptabilite SYCEBNL',
  'Provision maintenance annuelle',
];
